name: Code Review
description: Make some checks useful during Code Review

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

    - name: Setup node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      with:
        node-version-file: '.node-version'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Compile source code
      shell: bash
      run: npm run compile
