name: Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  code_review:
    name: Code Review Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - uses: ./.github/actions/code-review
