name: Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  code_review:
    name: Code Review Checks
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/code-review
