name: Before merge

on:
  merge_group:
    types: [checks_requested]

jobs:
  before_merge:
    name: Check before merge
    runs-on: ubuntu-latest

    steps:
      - name: Code Review
        uses: ./.github/actions/code-review
